# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Community Shaders Documentation
site_url: https://fenrirkey.github.io/
repo_url: https://github.com/doodlum/skyrim-community-shaders
repo_name: doodlum/skyrim-community-shaders
theme:
  name: material
  font:
    text: Open Sans
    code: Red Hat Mono
  icon:
    logo: material/library
    repo: fontawesome/brands/github
  #  logo: fontawesome/solid/c    
  features:
    - navigation.instant
    - navigation.footer
    - header.autohide
  custom_dir:  overrides/
  language: en 
extra:
  version:
    provider: mike
  social:
    - icon: nexus/nexus-mods-svgrepo-com
      link: https://www.nexusmods.com/skyrimspecialedition/mods/86492
    - icon: fontawesome/brands/discord
      link: https://discord.gg/nkrQybAsyy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: yellow
      accent: amber
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: blue grey
      accent: grey
        
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons